source 0_install_prerequisites.sh
source 1_cross_compile_kernel.sh
source 2_get_fsbl.sh
source 3_cross_compile_u-boot.sh
source 4_generate_bootimage.sh
source 5_device_tree.sh
source 6_cross_compile_rootfs.sh
source 7_installation_instructions.sh