FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y bc python make \
    u-boot-tools libncurses-dev \
    device-tree-compiler gparted git \
    build-essential libssl1.0-dev wget \
    cpio unzip rsync

CMD ["bash"]