#ifndef _CUSTOM_GPIO_MEMORY_MAP_
#define _CUSTOM_GPIO_MEMORY_MAP_

#define CUSTOM_GPIO_LED_BASE    0x43C00000
#define CUSTOM_GPIO_SW_BASE     0x43C20000

#define CUSTOM_GPIO_DATA_REG_OFFSET    0x0
#define CUSTOM_GPIO_MODE_REG_OFFSET    0x4
#define CUSTOM_GPIO_INT_EN_REG_OFFSET  0x8
#define CUSTOM_GPIO_PENDING_INT_OFFSET 0xC

// Mode register macros
#define CUSTOM_GPIO_MODE_READ           0X00000000U
#define CUSTOM_GPIO_MODE_WRITE          0XFFFFFFFFU

// Mode register macros
#define CUSTOM_GPIO_GLOBAL_INT_DISABLE  0X00000000U
#define CUSTOM_GPIO_GLOBAL_INT_ENABLE   0XFFFFFFFFU

#endif /* _CUSTOM_GPIO_MEMORY_MAP_ */
